//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfMerger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfMerger.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new keyword.
        /// </summary>
        internal static string AddNewKeyword {
            get {
                return ResourceManager.GetString("AddNewKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahmenbreite:.
        /// </summary>
        internal static string BorderWidth {
            get {
                return ResourceManager.GetString("BorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add keyword.
        /// </summary>
        internal static string buttonAddKeyword {
            get {
                return ResourceManager.GetString("buttonAddKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PDF.
        /// </summary>
        internal static string ButtonAddPdf {
            get {
                return ResourceManager.GetString("ButtonAddPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected page/PDF.
        /// </summary>
        internal static string ButtonRemovePdf {
            get {
                return ResourceManager.GetString("ButtonRemovePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and close.
        /// </summary>
        internal static string ButtonSaveAndClose {
            get {
                return ResourceManager.GetString("ButtonSaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export merged PDF.
        /// </summary>
        internal static string ButtonSavePdf {
            get {
                return ResourceManager.GetString("ButtonSavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string ButtonSaveProject {
            get {
                return ResourceManager.GetString("ButtonSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a border around the PDF-page.
        /// </summary>
        internal static string CBAddBorder {
            get {
                return ResourceManager.GetString("CBAddBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the Producer field on pdf export?.
        /// </summary>
        internal static string CBClearProducer {
            get {
                return ResourceManager.GetString("CBClearProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load every page when adding a pdf file.
        /// </summary>
        internal static string CBLoadEveryPage {
            get {
                return ResourceManager.GetString("CBLoadEveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project as Bundle (inkl. all pdf files in the project file).
        /// </summary>
        internal static string CBSaveAsBundle {
            get {
                return ResourceManager.GetString("CBSaveAsBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show filename extension in page tiles.
        /// </summary>
        internal static string CBShowFilenameExtension {
            get {
                return ResourceManager.GetString("CBShowFilenameExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a white background to the rendered PDF page.
        /// </summary>
        internal static string CBWhiteBackground {
            get {
                return ResourceManager.GetString("CBWhiteBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Recent Projects.
        /// </summary>
        internal static string ClearRecentProjects {
            get {
                return ResourceManager.GetString("ClearRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application color mode (experimental).
        /// </summary>
        internal static string ColorMode {
            get {
                return ResourceManager.GetString("ColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string ColorModeClassic {
            get {
                return ResourceManager.GetString("ColorModeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ColorModeDark {
            get {
                return ResourceManager.GetString("ColorModeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (changes apply after a program restart).
        /// </summary>
        internal static string ColorModeRestart {
            get {
                return ResourceManager.GetString("ColorModeRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ColorModeSystem {
            get {
                return ResourceManager.GetString("ColorModeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression level when saving project as bundle.
        /// </summary>
        internal static string CompressionLevelText {
            get {
                return ResourceManager.GetString("CompressionLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading project!.
        /// </summary>
        internal static string ErrorLoadingProject {
            get {
                return ResourceManager.GetString("ErrorLoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error merging/saving PDF.
        /// </summary>
        internal static string ErrorMergingPdf {
            get {
                return ResourceManager.GetString("ErrorMergingPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error merging or saving PDF file..
        /// </summary>
        internal static string ErrorMergingPdfMsg {
            get {
                return ResourceManager.GetString("ErrorMergingPdfMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving project!.
        /// </summary>
        internal static string ErrorSavingProject {
            get {
                return ResourceManager.GetString("ErrorSavingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FileMenuClose {
            get {
                return ResourceManager.GetString("FileMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export merged PDF.
        /// </summary>
        internal static string FileMenuExportMergedPdf {
            get {
                return ResourceManager.GetString("FileMenuExportMergedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load project.
        /// </summary>
        internal static string FileMenuLoadProject {
            get {
                return ResourceManager.GetString("FileMenuLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        internal static string FileMenuNewProject {
            get {
                return ResourceManager.GetString("FileMenuNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent projects ....
        /// </summary>
        internal static string FileMenuRecentProjects {
            get {
                return ResourceManager.GetString("FileMenuRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string FileMenuSaveProject {
            get {
                return ResourceManager.GetString("FileMenuSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project as.
        /// </summary>
        internal static string FileMenuSaveProjectAs {
            get {
                return ResourceManager.GetString("FileMenuSaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string FileMenuSettings {
            get {
                return ResourceManager.GetString("FileMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string LabeCreated {
            get {
                return ResourceManager.GetString("LabeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading project....
        /// </summary>
        internal static string LoadingProject {
            get {
                return ResourceManager.GetString("LoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging PDFs....
        /// </summary>
        internal static string MergingPdfs {
            get {
                return ResourceManager.GetString("MergingPdfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent projects.
        /// </summary>
        internal static string NoRecentProjects {
            get {
                return ResourceManager.GetString("NoRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF file.
        /// </summary>
        internal static string PdfFile {
            get {
                return ResourceManager.GetString("PdfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files.
        /// </summary>
        internal static string PdfFiles {
            get {
                return ResourceManager.GetString("PdfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFium License.
        /// </summary>
        internal static string PDFiumLicense {
            get {
                return ResourceManager.GetString("PDFiumLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFiumSharp License.
        /// </summary>
        internal static string PDFiumSharpLicense {
            get {
                return ResourceManager.GetString("PDFiumSharpLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFs merged successfully!.
        /// </summary>
        internal static string PDFMergedSuccess {
            get {
                return ResourceManager.GetString("PDFMergedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Merger Bundle.
        /// </summary>
        internal static string PdfMergerBundleFile {
            get {
                return ResourceManager.GetString("PdfMergerBundleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Merger.
        /// </summary>
        internal static string PDFMergerFile {
            get {
                return ResourceManager.GetString("PDFMergerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Merger files.
        /// </summary>
        internal static string PDFMergerFiles {
            get {
                return ResourceManager.GetString("PDFMergerFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Merger License.
        /// </summary>
        internal static string PDFMergerLicense {
            get {
                return ResourceManager.GetString("PDFMergerLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDfsharp License.
        /// </summary>
        internal static string PDfsharpLicense {
            get {
                return ResourceManager.GetString("PDfsharpLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string ProjectHelp {
            get {
                return ResourceManager.GetString("ProjectHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ProjectHelpAbout {
            get {
                return ResourceManager.GetString("ProjectHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string ProjectHelpLicenses {
            get {
                return ResourceManager.GetString("ProjectHelpLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string ProjectMenu {
            get {
                return ResourceManager.GetString("ProjectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PDF.
        /// </summary>
        internal static string ProjectMenuAddPdf {
            get {
                return ResourceManager.GetString("ProjectMenuAddPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit metadata for merged PDF .
        /// </summary>
        internal static string ProjectMenuEditMetadat {
            get {
                return ResourceManager.GetString("ProjectMenuEditMetadat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export merged PDF.
        /// </summary>
        internal static string ProjectMenuExportPdf {
            get {
                return ResourceManager.GetString("ProjectMenuExportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string ProjectMenuRedo {
            get {
                return ResourceManager.GetString("ProjectMenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected page/PDF.
        /// </summary>
        internal static string ProjectMenuRemovePdf {
            get {
                return ResourceManager.GetString("ProjectMenuRemovePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string ProjectMenuUndo {
            get {
                return ResourceManager.GetString("ProjectMenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project saved successfully!.
        /// </summary>
        internal static string ProjectSaveSuccess {
            get {
                return ResourceManager.GetString("ProjectSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render settings.
        /// </summary>
        internal static string RenderSettings {
            get {
                return ResourceManager.GetString("RenderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving project....
        /// </summary>
        internal static string SavingProject {
            get {
                return ResourceManager.GetString("SavingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialLog License.
        /// </summary>
        internal static string SerialLogLicense {
            get {
                return ResourceManager.GetString("SerialLogLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Buttons.
        /// </summary>
        internal static string SidebarAction {
            get {
                return ResourceManager.GetString("SidebarAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of documents.
        /// </summary>
        internal static string SidebarListOfDocs {
            get {
                return ResourceManager.GetString("SidebarListOfDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string SidebarPreview {
            get {
                return ResourceManager.GetString("SidebarPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string SidebarProject {
            get {
                return ResourceManager.GetString("SidebarProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF metadata editor.
        /// </summary>
        internal static string TitleMetadataEditor {
            get {
                return ResourceManager.GetString("TitleMetadataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused keywords.
        /// </summary>
        internal static string UnusedKeywords {
            get {
                return ResourceManager.GetString("UnusedKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding PDFs....
        /// </summary>
        internal static string WaitingPdfs {
            get {
                return ResourceManager.GetString("WaitingPdfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fastest.
        /// </summary>
        internal static string ZipCompressionFastest {
            get {
                return ResourceManager.GetString("ZipCompressionFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no compression.
        /// </summary>
        internal static string ZipCompressionNoCompression {
            get {
                return ResourceManager.GetString("ZipCompressionNoCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optimal.
        /// </summary>
        internal static string ZipCompressionOptimal {
            get {
                return ResourceManager.GetString("ZipCompressionOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smallest size.
        /// </summary>
        internal static string ZipCompressionSmallestSize {
            get {
                return ResourceManager.GetString("ZipCompressionSmallestSize", resourceCulture);
            }
        }
    }
}
